### ISSUE TITLE
pcre2 incorrectly parses `[.][^.]*$`.

### ISSUE THREAD

**Issue by fragmede** [PCRE2Project/pcre2#280] opened 2023-08-08 23:43 UTC
Hi, 

pcre2 incorrectly parses `[.][^.]*$`.

When I use [ag](https://github.com/ggreer/the_silver_searcher), which uses pcre2, vs [ripgrep](https://github.com/BurntSushi/ripgrep), which uses rust's implementation of regexp, I get:

```
fragmede@samairmac:~/projects/ag_bug$ find . | ag -o  [.][^.]*$ | sort -u  | tail -3
./the_silver_searcher/tests/word_regexp.t
./the_silver_searcher/the_silver_searcher.spec
./the_silver_searcher/the_silver_searcher.spec.in
fragmede@samairmac:~/projects/ag_bug$ find . | rg -o  [.][^.]*$ | sort -u  | tail -3
.w32
.yml
.zig
fragmede@samairmac:~/projects/ag_bug$
```

**Comment by BurntSushi** [comment] 2023-08-08 23:49
Looks like it could be an `ag` bug? If you tell ripgrep to use PCRE2, then it gets the same result:

```
$ git remote -v
origin  git@github.com:ggreer/the_silver_searcher (fetch)
origin  git@github.com:ggreer/the_silver_searcher (push)
$ git rev-parse HEAD
a61f1780b64266587e7bc30f0f5f71c6cca97c0f
$ find . | rg -P -o [.][^.]*$ | sort -u | tail -3
.txt
.w32
.yml
```

Note also that `ag` uses PCRE, not PCRE2. ripgrep uses PCRE2.

**Comment by fragmede** [comment] 2023-08-09 05:34
Ah thanks. Got confused tracking down dependencies. I'll file it with ag directly.

**Comment by PhilipHazel** [comment] 2023-08-27 15:16
Closing this issue as not a bug.

**Closed by PhilipHazel** 2023-08-27 15:16 UTC
