### ISSUE TITLE
Bug in one or more quantifier since PCRE10.35/PHP7.4.12

### ISSUE THREAD

**Issue by mickmackusa** [PCRE2Project/pcre2#133] opened 2022-07-09 00:10 UTC
Reproduce with: [3v4l Demo](https://3v4l.org/4ftgl) 

```
$txt = <<<TEXT
foo {
     A
}

foo {
     A
}

foo {
     B
}

foo {
     A
}

foo {
     C
}
TEXT;
echo preg_replace('/\R{0,2}.+{[^}]*A[^}]*}/', '', $txt);
```

Expected Result:

```
foo {
     B
}

foo {
     C
}
```

Actual Result:

```
foo {
     B
}

foo {
     A
}

foo {
     C
}
```

**Comment by cmb69** [comment] 2022-07-11 11:35
I can reproduce this with pcre2test (build form 3e52db52093ad104fb7be2fda12cbdae91cea2a0):
````
cmb@ELEPHPANT:~$ pcre2test test.txt
PCRE2 version 10.41 2022-xx-xx
/\n{0,2}.+{[^}]*A[^}]*}/g
foo {\n    A\n}\n\nfoo {\n    A\n}\n\nfoo {\n    B\n}\n\nfoo {\n    A\n}\n\nfoo {\n    C\n}
 0: foo {\x0a    A\x0a}
 0: \x0a\x0afoo {\x0a    A\x0a}
 0: \x0a\x0afoo {\x0a    A\x0a}
cmb@ELEPHPANT:~$ pcre2test -jit test.txt
PCRE2 version 10.41 2022-xx-xx
/\n{0,2}.+{[^}]*A[^}]*}/g
foo {\n    A\n}\n\nfoo {\n    A\n}\n\nfoo {\n    B\n}\n\nfoo {\n    A\n}\n\nfoo {\n    C\n}
 0: foo {\x0a    A\x0a}
 0: \x0a\x0afoo {\x0a    A\x0a}
````
So this looks like a JIT issue.

**Comment by zherczeg** [comment] 2022-07-12 08:39
Thank you for the report. Proposed fix: #135

**Comment by cmb69** [comment] 2022-07-12 09:24
Thank you for the quick reply! I can confirm that #135 solves this issue for me, and apparently causes no unwanted side effects.

**Comment by PhilipHazel** [comment] 2022-07-15 16:09
#135 is now merged.

**Closed by PhilipHazel** 2022-07-15 16:09 UTC
