### ISSUE TITLE
I use pcre2 to do text postprocessing, and encountered a core problem.

### ISSUE THREAD

**Issue by housebaby** [PCRE2Project/pcre2#40] opened 2021-11-09 09:12 UTC
Can anyone git me a hint about this problem 
No idea how to fix  it 
![image](https://user-images.githubusercontent.com/9246556/140895981-26dc8393-53e4-4161-a1f4-0bc5829941fd.png)

**Comment by zherczeg** [comment] 2021-11-09 11:21
Could you share a pattern and some minimal input where the issue can be reproduced?

**Comment by PhilipHazel** [comment] 2022-04-23 14:01
I am closing this because no more information has been provided.

**Closed by PhilipHazel** 2022-04-23 14:01 UTC
